name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.4, 8.0]

    steps:
      - name: ğŸ“¤ Checkout project
        uses: actions/checkout@v3

      - name: ğŸ˜ Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: ğŸ“¦ Install dependencies
        run: composer install --no-progress --no-suggest

      - name: âœ… Run tests
        run: vendor/bin/phpunit